version: '0.3'

services:

# ============================= DATABASES =============================

  app_db:
    image: postgres
    volumes:
      - ./app_db_node/db:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  oidc_db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./kc_db_node/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # ============================= OpenID Connect =============================

  oidc:
    build: keycloak_node
    ports:
      - "8080:8080"
    command: start-dev --db-url="jdbc:postgresql://oidc_db:5432/postgres" --db-username=postgres --db-password=postgres
    environment:
#      - KC_HOSTNAME=oidc
      - KC_DB=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    depends_on:
      - oidc_db

   # ============================= Web Front =============================

  web:
    build: django_node
    command: sh -c "pytest django_node/static_tests && python django_node/manage.py runserver 0.0.0.0:8000"
    restart: "on-failure"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=app_db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5433
    depends_on:
      - app_db
      - oidc

  # ============================= Back Engine =============================
  #  app_engine:

#  CALL DYNAMIC TEST FROM API
#  dynamic_test:
#    build: django_node
#    volumes:
#      - .:/code
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db
#      - web
#    command: pytest django_node/dynamic_tests