version: '1.0.0'

services:

# ============================= DATABASES =============================

  django_db:

    image: postgres

    container_name: django_db_node

    volumes:
      - ./django_db_node/db:/var/lib/postgresql/data

    expose:
      - "5433"

    ports:
      - "5433:5432"

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    healthcheck:
      test: [ "CMD", "pg_isready", "-p 5433", "-U", "postgres" ]
      interval: 5s
      timeout: 30s
      retries: 10

    command : -p 5433

   # ============================= Web Front =============================

  django_node:
    build: django_node
    container_name: django_node
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=django_db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5433
    depends_on:
      django_db:
        condition: service_healthy
#      - oidc

  # ============================= Back Engine =============================
  #  app_engine:

#  CALL DYNAMIC TEST FROM API
#  dynamic_test:
#    build: django_node
#    volumes:
#      - .:/code
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db
#      - web
#    command: pytest django_node/dynamic_tests

  # ============================= OpenID Connect DATABASE =============================

#  oidc_db:
#    image: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./kc_db_node/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres

  # ============================= OpenID Connect =============================

#  oidc:
#    build: keycloak_node
#    ports:
#      - "8080:8080"
#    command: start-dev --db-url="jdbc:postgresql://oidc_db:5432/postgres" --db-username=postgres --db-password=postgres
#    restart: "always"
#    environment:
##      - KC_HOSTNAME=oidc
#      - KC_DB=postgres
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    depends_on:
#      - oidc_db