version: '4.19.0'

services:

# ============================= DATABASES =============================

  django_db:

    image: postgres

    container_name: django_db_node

    volumes:
      - ./django_db_node/db:/var/lib/postgresql/data

    expose:
      - "5433"

    ports:
      - "5433:5432"

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    healthcheck:
      test: [ "CMD", "pg_isready", "-p 5433", "-U", "postgres" ]
      interval: 5s
      timeout: 30s
      retries: 10

    command : -p 5433

   # ============================= Web Django Front =============================

  django_node:
    build: django_node
    container_name: django_node
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=django_db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5433

      - ENGINE_HOST=engine_node
      - ENGINE_PORT=80
    depends_on:
      django_db:
        condition: service_healthy
#      - oidc

  # ============================= FastAPI Back Engine =============================

  engine_node:
    build: engine_node
    container_name: engine_node
    command : ["uvicorn", "main_uvicorn:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - .:/code
    ports:
      - "80:80"

  # ============================= OpenID Connect DATABASE =============================

#  oidc_db:
#    image: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./kc_db_node/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres

  # ============================= OpenID Connect =============================

#  oidc:
#    build: keycloak_node
#    ports:
#      - "8080:8080"
#    command: start-dev --db-url="jdbc:postgresql://oidc_db:5432/postgres" --db-username=postgres --db-password=postgres
#    restart: "always"
#    environment:
##      - KC_HOSTNAME=oidc
#      - KC_DB=postgres
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    depends_on:
#      - oidc_db