"""
Django settings for web_app project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# sys.path.append(str(BASE_DIR))
# from web_app.middleware import KeycloakMiddleware

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-36fjz=v-5&a&*(aop^6cjd6m5a!$^xy)kl-7=2i7p$br1%7ydq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # APPS

    'home',
    'notes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'static/templates/',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_NAME'),
        'USER': os.environ.get('POSTGRES_USER'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
        'HOST': os.environ.get('POSTGRES_HOST'),
        'PORT': os.environ.get('POSTGRES_PORT'),
    }
}

# AUTH_SERVER_ROOT = 'http://oidc:8080/auth'  # L'URL de votre Keycloak
# OIDC_RP_CLIENT_ID = "django_client"  # L'ID de votre client dans Keycloak
# OIDC_RP_CLIENT_SECRET = "ZUGw40WxeKqBG16kxx9UalgeKecgx7jW"  # Le secret d'authentification de votre client pour la connexion
# KEYCLOAK_REALM = 'dev_sec_ops'
# KEYCLOAK_CLIENT_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
# MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy/63fMsGM2RD9waqvfBbxJxiHY8q4HMulD+QxjVDSsuWMKdaBZvwLRf0/qwr9jhXG+wNcuq7p0dxumo9VW0tkPmmhJh9Y5RVHImz8gnzRCWIBWM5evyav+ipDZEEq6BUQ0CSwUU8cz5LeD6YXt+9LH2AmEcoGhppU3w7LpvTyoawJ01RV7yLbQBC1CH2Yx78Vb0OcayFZPB4EmswNEimbxjh4F41lu9j1KP441lZewefriiCV2Rs2Li7FdGRFb4qTC30TE9IKV+BpjTRtuP1aVbqPPa3p5jFNAd3cVahvxb+3KSo3O8DtJNmr1ejWljU4Mfg6eSWWGMEbH60au9/UQIDAQAB
# -----END PUBLIC KEY-----"""

# Excempt list - URL paths that doesn't need Keycloak Authorization
# KEYCLOAK_BEARER_AUTHENTICATION_EXEMPT_PATHS = [
#     'admin', 'accounts',
#     ]

CONFIG_DIR = f"{BASE_DIR}/config/"

#
# KEYCLOAK_CONFIG = {
#     'KEYCLOAK_REALM': os.environ.get('KEYCLOAK_REALM'),
#     'KEYCLOAK_CLIENT_ID': os.environ.get('OIDC_RP_CLIENT_ID'),
#     'KEYCLOAK_DEFAULT_ACCESS': 'ALLOW', # DENY or ALLOW
#     'KEYCLOAK_AUTHORIZATION_CONFIG': os.path.join(CONFIG_DIR, 'authorization-config.json'),
#     'KEYCLOAK_METHOD_VALIDATE_TOKEN': 'DECODE',
#     'KEYCLOAK_SERVER_URL': os.environ.get('AUTH_SERVER_ROOT'),
#     'KEYCLOAK_CLIENT_SECRET_KEY': os.environ.get('OIDC_RP_CLIENT_SECRET'),
#     'KEYCLOAK_CLIENT_PUBLIC_KEY': KEYCLOAK_CLIENT_PUBLIC_KEY,
# }



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIR = [
    f"{BASE_DIR}/static/",
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
